export const APP_NAME = 'STYN';
export const ADMIN_EMAILS = ['datingwithbounce@gmail.com', 'raymondsurv@gmail.com'];
export const FOOTER_TEXT = '© 2026. All rights reserved.';

export const COUNTRIES_AND_CITIES: { [country: string]: string[] } = {
  'Algeria': ['Algiers', 'Oran', 'Constantine', 'Batna', 'Djelfa'],
  'Angola': ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Lubango'],
  'Benin': ['Cotonou', 'Abomey-Calavi', 'Porto-Novo', 'Parakou', 'Djougou'],
  'Botswana': ['Gaborone', 'Francistown', 'Molepolole', 'Maun', 'Serowe'],
  'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora'],
  'Burundi': ['Bujumbura', 'Gitega', 'Muyinga', 'Ngozi', 'Ruyigi'],
  'Cameroon': ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua'],
  'Cape Verde': ['Praia', 'Mindelo', 'Santa Maria', 'Espargos', 'Assomada'],
  'Central African Republic': ['Bangui', 'Bimbo', 'Mbaïki', 'Berbérati', 'Kaga-Bandoro'],
  'Chad': ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kélo'],
  'Comoros': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Mirontsi'],
  'Congo (Brazzaville)': ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Madingou', 'Oyo'],
  'Congo (Kinshasa)': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'],
  'Djibouti': ['Djibouti City', 'Ali Sabieh', 'Tadjoura', 'Obock', 'Dikhil'],
  'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said'],
  'Equatorial Guinea': ['Malabo', 'Bata', 'Ebebiyín', 'Mongomo', 'Luba'],
  'Eritrea': ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera'],
  'Eswatini': ['Mbabane', 'Manzini', 'Big Bend', 'Mhlume', 'Nhlangano'],
  'Ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mek\'ele', 'Gondar', 'Adama'],
  'Gabon': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'],
  'Gambia': ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni'],
  'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Ashaiman'],
  'Guinea': ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Labé'],
  'Guinea-Bissau': ['Bissau', 'Bafatá', 'Gabú', 'Bissora', 'Bolama'],
  'Ivory Coast': ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'Korhogo'],
  'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
  'Lesotho': ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse', 'Mohale\'s Hoek'],
  'Liberia': ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville', 'Harper'],
  'Libya': ['Tripoli', 'Benghazi', 'Misrata', 'Bayda', 'Zawiya'],
  'Madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Fianarantsoa'],
  'Malawi': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Kasungu'],
  'Mali': ['Bamako', 'Sikasso', 'Kalabancoro', 'Koutiala', 'Ségou'],
  'Mauritania': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Adel Bagrou', 'Boghé'],
  'Mauritius': ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes'],
  'Morocco': ['Casablanca', 'Fez', 'Tangier', 'Marrakesh', 'Salé'],
  'Mozambique': ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio'],
  'Namibia': ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Henties Bay', 'Oshakati'],
  'Niger': ['Niamey', 'Zinder', 'Maradi', 'Tahoua', 'Agadez'],
  'Nigeria': ['Lagos', 'Kano', 'Ibadan', 'Benin City', 'Port Harcourt'],
  'Rwanda': ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi'],
  'Sao Tome and Principe': ['São Tomé', 'Trindade', 'Santana', 'Neves', 'Santo Amaro'],
  'Senegal': ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Kaolack'],
  'Seychelles': ['Victoria', 'Anse Etoile', 'Beau Vallon', 'Anse Royale', 'Cascades'],
  'Sierra Leone': ['Freetown', 'Kenema', 'Bo', 'Koidu', 'Makeni'],
  'Somalia': ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo', 'Merca'],
  'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Soweto'],
  'South Sudan': ['Juba', 'Yei', 'Wau', 'Malakal', 'Nimule'],
  'Sudan': ['Khartoum', 'Omdurman', 'Nyala', 'Port Sudan', 'Kassala'],
  'Tanzania': ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya'],
  'Togo': ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé'],
  'Tunisia': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen-Mnihla', 'Kairouan'],
  'Uganda': ['Kampala', 'Nansana', 'Kira', 'Ssabagabo', 'Mbarara'],
  'Zambia': ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola'],
  'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Epworth'],
  'United Kingdom': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool'],
  'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
};

export const RELATIONSHIP_STATUSES = [
  'Single',
  'In a relationship',
  'Married',
  'Engaged',
  'It\'s complicated',
  'Separated',
  'Divorced',
  'Widowed'
];
